---
title: "car_accident_initial_analysis"
author: "Alejandro Calderon, Dylan Craker, Trent Douglas"
date: "5/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
library(lubridate)
library(grDevices)
library(ggplot2)
```


```{r load, include=FALSE}
baton_rouge_data <- read.csv("data/Baton_Rouge_Traffic_Incidents.csv")
seattle_data <- read.csv("data/seattle_Collisions.csv")
tempe_data <- read.csv("data/tempe_Crash_Data_Report__detail_.csv")
national_data <- read_xlsx("data/nhtsa_yearly_national_stats.xlsx")
```

## Filtering datasets
```{r baton_rouge_maniputalion, include=FALSE}
baton_rouge <- select(baton_rouge_data, CRASH.DATE, OCCURED.ON, FATALITY, INJURY, PRIMARY.FACTOR, SECOND.FACTOR, PEDESTRIAN)
br_dataframe <- sapply(baton_rouge, is.factor)
baton_rouge[br_dataframe] <- lapply(baton_rouge[br_dataframe], function(FATALITY) as.numeric(as.character(FATALITY)))
transform(baton_rouge, FATALITY =as.numeric(FATALITY))

baton_rouge$DATE <- strptime(as.character(baton_rouge$CRASH.DATE), "%m/%d/%Y")
baton_rouge$DATE <- format(baton_rouge$DATE, "%Y")
br_data <- select(baton_rouge, OCCURED.ON, FATALITY, INJURY, PRIMARY.FACTOR, SECOND.FACTOR, PEDESTRIAN, DATE)
```

```{r baton_rouge_data_cleaning}
br_data$FATALITY[br_data$FATALITY == ""] <- 0
br_data$FATALITY[br_data$FATALITY == "X"] <- 1
br_data$FATALITY <- as.numeric(br_data$FATALITY)

br_data$INJURY[br_data$INJURY == ""] <- as.numeric(0)
br_data$INJURY[br_data$INJURY == "X"] <- as.numeric(1)
br_data$INJURY <- as.numeric(br_data$INJURY)

br_data$PEDESTRIAN[br_data$PEDESTRIAN == ""] <- as.numeric(0)
br_data$PEDESTRIAN[br_data$PEDESTRIAN == "X"] <- as.numeric(1)
br_data$PEDESTRIAN <- as.numeric(br_data$PEDESTRIAN)

br_data$SECOND.FACTOR[br_data$SECOND.FACTOR == ""] <- "NONE"

br_summary <- summary(br_data)
br_summary
```

```{r br_desc_stats}
primary_factors_br <- unique(br_data$PRIMARY.FACTOR)

accident_totals <- br_data %>% group_by("primary_reason" = br_data$PRIMARY.FACTOR) %>% count()
year_totals <- br_data %>% group_by("year" = br_data$DATE) %>% count()

br_fatality <- subset(br_data, subset = (FATALITY == "1")) 
fatality_counts <- br_data %>% group_by(DATE) %>% filter(FATALITY == 1) %>% count()
fatality_counts$DATE <- as.numeric(fatality_counts$DATE)

br_no_fatality <- subset(br_data, subset = (FATALITY == 0))
no_fatality_count <- br_no_fatality %>% group_by(DATE) %>% count()
no_fatality_count$DATE <- as.numeric(no_fatality_count$DATE)

fatality_totals <- c(fatality_counts$n, no_fatality_count$n)

fatality_plot <- ggplot() +
  geom_point(data = fatality_counts, aes(DATE, n))+
  geom_point(data = no_fatality_count, aes(DATE, n))+
  xlim(c(2010, 2021)) +
  scale_y_continuous(trans = 'log2') +
  ylab("Total Number of Fatalities") +
  xlab("Year")
print(fatality_plot + ggtitle("Number of Car Accidents in Baton Rouge from 2010-2021"))

lm_fatality <- lm(br)

fatality_count_br <- br_fatality %>% group_by(br_fatality$DATE) %>% count()
no_fatality_count_br <- br_no_fatality %>% group_by(br_no_fatality$DATE) %>% count()

br_desc_plot <- ggplot(accident_totals, aes(x=n, y=primary_reason)) +
  geom_bar(stat="identity") +
  ylab("Cause of Accident") +
  xlab("Frequency") +
  scale_x_continuous(trans = 'log2')
print(br_desc_plot + ggtitle("Cause of Car Accidents in Baton Rouge from 2010-2021"))

summary(accident_totals$n)
```

```{r br_function_extra, include=FALSE}
# frequency_by_year <- function(data, variable_of_interest, time_variable, year){
#   counts <- table(data %>% group_by("variable_of_interest" = data$variable_of_interest) %>% count())
#   year_total <- filter()
#   
#   
#   return()
#} #finish function to return bar plot of accidents and yearly totals
```


```{r seattle}
##Filter unnecessary columns
seattle_data <- select(seattle_data, PERSONCOUNT, VEHCOUNT, INJURIES, SERIOUSINJURIES, FATALITIES, INCDTTM, JUNCTIONTYPE, UNDERINFL, WEATHER, ROADCOND, LIGHTCOND, SPEEDING)

##Change date to only year
seattle_data$date <- strptime(as.character(seattle_data$INCDTTM), "%m/%d/%Y")
seattle_data$date <- format(seattle_data$date, "%Y")

##Change blanks to NA
seattle_data$PERSONCOUNT[seattle_data$PERSONCOUNT == "0"] <- "NA"
seattle_data$VEHCOUNT[seattle_data$VEHCOUNT == "0"] <- "NA"
seattle_data$JUNCTIONTYPE[seattle_data$JUNCTIONTYPE == ""] <- "NA"
seattle_data$UNDERINFL[seattle_data$UNDERINFL == ""] <- "NA"
seattle_data$WEATHER[seattle_data$WEATHER == ""] <- "NA"
seattle_data$ROADCOND[seattle_data$ROADCOND == ""] <- "NA"
seattle_data$LIGHTCOND[seattle_data$LIGHTCOND == ""] <- "NA"
seattle_data$SPEEDING[seattle_data$SPEEDING == ""] <- "N"

##Subset to years in used in analysis
sea_data <- subset(seattle_data, subset = (date >= "2012" & date <= "2019"))

sea_data <- na.omit(sea_data)
sea_fatality <- subset(sea_data, subset = (FATALITIES >= "1"))
sea_no_fatality <- subset(sea_data, subset = (FATALITIES == "0"))

sea_data_summary <- summary(sea_data)
sea_data_summary
```

```{r tempe data manipulation}
#initial filter of columns
tempe_filter <- tempe_data %>%
  select(Year, Totalinjuries, Totalfatalities, Injuryseverity, AlcoholUse_Drv1,
         DrugUse_Drv1, Unitaction_One, Violation1_Drv1, StreetName, CrossStreet, Lightcondition,
         JunctionRelation,Weather, SurfaceCondition) 

#filters out blank rows
tempe_filter <- tempe_filter[!(tempe_filter$AlcoholUse_Drv1 == ""), ]
```

```{r tempe summary}
#2012-2019
count(tempe_filter, Totalfatalities > 0)
# only 87 accidents with fatalities

summary(tempe_filter)
```

```{r tempe injury plot}
#simple barplot
ggplot(tempe_filter) +
  geom_bar(aes(x = Injuryseverity)) +
  theme(axis.text.x = element_text(size = 6))
```
```{r tempe stacked bar plot}
#test dont work
ggplot(tempe_filter) +
  geom_bar(aes(x = Injuryseverity, y = n), stat = "Year")

#testing aggregating counts for stacked bar chart
tempe_aggregate <- count(tempe_filter, Year, Totalinjuries, AlcoholUse_Drv1)



tempe_ord <- mutate(tempe_aggregate,
                     Totalinjuries = reorder(Totalinjuries, -n, sum),
                     AlcoholUse_Drv1 = reorder(AlcoholUse_Drv1, -n, sum))


#stacked bar plot showing number of injuries in accordance to alcohol influence
tempe_alcinf <- ggplot(tempe_aggregate) +
  geom_col(aes(x = AlcoholUse_Drv1, y = n, fill = Totalinjuries))

#makes multiple charts for each year
tempe_alcinf + facet_wrap(~ Year)
 
#need to find proportions instead of counts to account for the much higher number
#of occurances for non-influence driving

#tempe populations for future reference
tempepop_2012 <- 164139
tempepop_2013 <- 164742
tempepop_2014 <- 166975
tempepop_2015 <- 169816
tempepop_2016 <- 174708
tempepop_2017 <- 178339
tempepop_2018 <- 183652
tempepop_2019 <- 187454

#tempe area mi^2
tempe_area <- 40.22
```
